/**
 * Chat utilities — shared logic used by both chat/page.js and chat/[id]/page.js
 *
 * Extracted to eliminate duplication (Handoff Report §3.2, Issue #1).
 * Any bug fix or improvement here applies to both pages automatically.
 */

import { useState } from "react";

/**
 * Detects if an AI message contains a question with selectable options.
 * Looks for patterns like lines ending with ? followed by bullet items.
 */
export function detectQuickReplies(content) {
  if (!content) return null;

  const lowerContent = content.toLowerCase();

  // Hardcoded fallbacks for common banking questions
  if (lowerContent.includes('conventional') && lowerContent.includes('islamic')) {
    return ["Conventional", "Islamic", "Either is fine"];
  }
  if ((lowerContent.includes('employment') || lowerContent.includes('occupation') || lowerContent.includes('profession')) && lowerContent.includes('?')) {
    return ["Student", "Salaried", "Self-employed", "Business Owner", "Other"];
  }

  // Smart detection: only pick up bullets that appear AFTER the last question
  // AND form the tail end of the message (i.e. they're the final content).
  const lastQuestionIdx = content.lastIndexOf('?');
  if (lastQuestionIdx === -1) return null; // No question = no quick replies

  const afterQuestion = content.slice(lastQuestionIdx + 1).trim();
  if (!afterQuestion) return null; // Nothing after the question

  const lines = afterQuestion.split('\n').map(l => l.trim()).filter(Boolean);
  const options = [];

  for (const line of lines) {
    const bulletMatch = line.match(/^[-*•]\s*(.+)$/);
    if (bulletMatch) {
      const text = bulletMatch[1].replace(/\*\*/g, '').replace(/\?$/, '').trim();
      // Only short, concise options (not full sentences or descriptions)
      if (text.length > 3 && text.length < 60 && !text.includes('.') && !text.includes(',')) {
        options.push(text);
      }
    }
  }

  // Only return if we got a reasonable number of short options
  // and there's nothing substantial AFTER the bullets (they must be the tail)
  if (options.length >= 2 && options.length <= 6) {
    // Verify bullets are truly the last content (no paragraphs after them)
    const lastBulletLine = lines[lines.length - 1];
    if (lastBulletLine && /^[-*•]\s*.+$/.test(lastBulletLine)) {
      return options;
    }
  }

  return null;
}


/**
 * Format agent name for display.
 * Converts snake_case to Title Case and renames "Triage Agent" to "AI Advisor".
 */
export function formatAgentName(name) {
  if (!name) return "";
  return name
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace("Triage Agent", "AI Advisor");
}


/**
 * Get initials from a full name for avatar display.
 */
export function getInitials(name) {
  if (!name) return "U";
  const parts = name.trim().split(/\s+/);
  if (parts.length === 1) return parts[0].charAt(0).toUpperCase();
  return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase();
}


/**
 * Convert markdown-like text to HTML.
 *
 * This is a custom regex parser tuned for our constrained AI output.
 * Handles: bold, italic, headings, code blocks, tables, lists, HR, paragraphs.
 *
 * NOTE: This works because the AI prompts enforce strict markdown formatting.
 * For unconstrained markdown, replace with react-markdown + remark-gfm.
 */
export function simpleMarkdown(text) {
  if (!text) return "";
  // Normalize excessive newlines (collapse 3+ into 2)
  let s = text.replace(/\n{3,}/g, "\n\n");
  // Escape HTML
  s = s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  
  // Fix escaped asterisks (\*) generated by LLM
  s = s.replace(/\\\*/g, "*");
  
  // Restore any <br> tags the LLM might have explicitly generated
  s = s.replace(/&lt;br\s*\/?&gt;/gi, "<br/>");
  
  // Bold and italic
  s = s.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
  s = s.replace(/\*(.*?)\*/g, "<em>$1</em>");
  // Headings
  s = s.replace(/^### (.*$)/gm, "<h3>$1</h3>");
  s = s.replace(/^## (.*$)/gm, "<h2>$1</h2>");
  s = s.replace(/^# (.*$)/gm, "<h1>$1</h1>");
  // Code blocks
  s = s.replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>");
  s = s.replace(/`(.*?)`/g, "<code>$1</code>");
  // Tables — with proper header row
  s = s.replace(/^\|(.+)\|$/gm, (match) => {
    const cells = match.split("|").filter(Boolean).map((c) => c.trim());
    if (cells.every((c) => /^[-:]+$/.test(c))) return "__TABLE_SEP__";
    return `<tr>${cells.map((c) => `<td>${c}</td>`).join("")}</tr>`;
  });
  // Wrap consecutive rows into table, promote first row to th
  s = s.replace(/((?:<tr>.*<\/tr>\s*(?:__TABLE_SEP__\s*)?)+)/g, (block) => {
    const clean = block.replace(/__TABLE_SEP__\s*/g, "");
    // Promote first row cells from td to th
    const promoted = clean.replace(/<tr>(.*?)<\/tr>/, (firstRow, inner) => {
      return `<thead><tr>${inner.replace(/<td>/g, "<th>").replace(/<\/td>/g, "</th>")}</tr></thead>`;
    });
    return `<table>${promoted}</table>`;
  });
  s = s.replace(/__TABLE_SEP__/g, "");
  // HR
  s = s.replace(/^---$/gm, "<hr/>");
  // Unordered lists
  s = s.replace(/^[-*•] (.*$)/gm, "<li>$1</li>");
  s = s.replace(/((?:<li>.*<\/li>\s*)+)/g, "<ul>$1</ul>");
  // Ordered lists
  s = s.replace(/^\d+\. (.*$)/gm, "<li>$1</li>");
  
  // Force double newlines around block elements to ensure they are isolated
  s = s.replace(/(<h[1-3]>.*?<\/h[1-3]>)/g, "\n\n$1\n\n");
  s = s.replace(/(<table[\s\S]*?<\/table>)/g, "\n\n$1\n\n");
  s = s.replace(/(<ul[\s\S]*?<\/ul>)/g, "\n\n$1\n\n");
  s = s.replace(/(<pre[\s\S]*?<\/pre>)/g, "\n\n$1\n\n");
  s = s.replace(/(<hr\/>)/g, "\n\n$1\n\n");
  
  // Split into paragraphs
  const blocks = s.split(/\n\n+/);
  s = blocks.map(block => {
    block = block.trim();
    if (!block) return "";
    // If it's already a block element, don't wrap in <p>
    if (/^(<h[1-3]>|<table>|<ul>|<pre>|<hr\/>)/.test(block)) {
      return block;
    }
    // Convert remaining single newlines to <br/> and wrap in <p>
    return `<p>${block.replace(/\n/g, "<br/>")}</p>`;
  }).join("");
  
  return s;
}
